/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.ClienteDAO;
import dao.PacoteDAO;
import dao.FuncionarioDAO;
import dao.OrcamentoDAO;
import dao.ProdutoDAO;
import entity.Orcamento;
import entity.Produto;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utils.TableModelCreator;

/**
 *
 * @author vilyn
 */
public class Novo_evento extends javax.swing.JDialog {

    /**
     * Creates new form NewJFrame
     */
    private Orcamento objetoOrcamento;
    private entity.Pacote objetoPacote;
    private entity.Cliente clienteSelecionado;
    private entity.Produto objetoProduto;
    private entity.Lancamento objetoLancamento;
    private DefaultTableModel modelProd = null;
    private DefaultTableModel modelFunc = null;
    private DefaultTableModel modelLanc = null;
    private double equipe = 0;
    private int linhas;
    private int idSelecionado;

    public Novo_evento(java.awt.Frame parent, boolean modal, Orcamento objetoOrcamento, entity.Cliente clienteSelecionado, entity.Pacote objetoPacote, entity.Produto objetoProduto, entity.Lancamento objetoLancamento) {
        super(parent, modal);
        this.objetoPacote = objetoPacote;
        this.clienteSelecionado = clienteSelecionado;
        this.objetoOrcamento = objetoOrcamento;
        this.objetoProduto = objetoProduto;
        this.objetoLancamento = objetoLancamento;
        initComponents();
    }

    public int getLinhas() {
        return linhas;
    }

    public double getEquipe() {
        return equipe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbLocal = new javax.swing.JComboBox<>();
        lblEndereco = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDias = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNumeroConvidados = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        cmbTipoEvento = new javax.swing.JComboBox<>();
        btnProximo = new javax.swing.JButton();
        lblData1 = new javax.swing.JFormattedTextField();
        lblHoraroi = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItemIncluido = new javax.swing.JTable();
        cmbMaterial = new javax.swing.JRadioButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbAlimenticio = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        txtTipoProduto = new javax.swing.JTextField();
        txtValorProd = new javax.swing.JTextField();
        txtUnidadeProd = new javax.swing.JTextField();
        txtPrecoFinalProd = new javax.swing.JTextField();
        txtQtdProd = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        btnProx = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jTextField18 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnIncluirFunc = new javax.swing.JButton();
        txtNomeFunc = new javax.swing.JTextField();
        txtCelFunc = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtFuncaoFunc = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        txtSalFunc = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFuncIncluido = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        jLabel57 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        btnExcluir1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtValorEquipe = new javax.swing.JTextField();
        txtValorDesconto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtValorServico = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtValorItens = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtValorFinal = new javax.swing.JTextField();
        btnProxOrc = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtValorOriginal = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        cmbPagamento = new javax.swing.JComboBox<>();
        txtParcelas = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtDescontoParcela = new javax.swing.JTextField();
        txtValorParcela = new javax.swing.JTextField();
        txtTotalParcela = new javax.swing.JTextField();
        btnFatura = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        txtValorEntrada = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        cmbOrcamento = new javax.swing.JComboBox<>();
        cmbCliente1 = new javax.swing.JComboBox<>();
        txtDataVencimento = new javax.swing.JFormattedTextField();
        cmbId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Evento");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbLocal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Casa", "Chacará", "Clube", "Igreja", "Outros" }));

        lblEndereco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDescricao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("Novo evento");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Nome do cliente:");

        btnLimpar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-apagar-16.png"))); // NOI18N
        btnLimpar.setText("Limpar");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de evento:");

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-cancelar-16.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nº de convidados:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Endereço:");

        lblDias.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Descrição:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Horário:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("------------------------------------");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Local do evento:");

        lblNumeroConvidados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Quantos dias vai durar o evento:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Data:");

        cmbCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbCliente.setToolTipText("");

        cmbTipoEvento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aniversário", "Casamento", "Infanfil", "Happy hour", "Outros" }));

        btnProximo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-à-direita-dentro-de-um-círculo-16_1.png"))); // NOI18N
        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        try {
            lblData1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            lblHoraroi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProximo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEndereco)
                                    .addComponent(lblDescricao)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblData1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHoraroi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDias, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumeroConvidados, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(451, 451, 451)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel11)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblNumeroConvidados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(lblData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraroi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnLimpar)
                    .addComponent(btnProximo))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Evento", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblItemIncluido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade", "Tipo", "Preço"
            }
        ));
        jScrollPane2.setViewportView(tblItemIncluido);

        cmbMaterial.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbMaterial.setText("Material");
        cmbMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMaterialActionPerformed(evt);
            }
        });

        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Tipo de item:");

        cmbAlimenticio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbAlimenticio.setText("Alimenticio");
        cmbAlimenticio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlimenticioActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setText("Itens incluídos no pacote");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-detetive-16.png"))); // NOI18N
        jLabel16.setText("Busca:");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Nome:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Tipo:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Preço unitário:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Unidade de medida:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Quantidade");

        btnIncluir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-mais-16.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Preço Final:");

        txtNomeProduto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNomeProduto.setEnabled(false);

        txtTipoProduto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTipoProduto.setEnabled(false);

        txtValorProd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtUnidadeProd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUnidadeProd.setEnabled(false);

        txtPrecoFinalProd.setEditable(false);
        txtPrecoFinalProd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtQtdProd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtQtdProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtdProdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoProduto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoFinalProd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnidadeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19)
                    .addComponent(txtUnidadeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(btnIncluir)
                    .addComponent(jLabel21)
                    .addComponent(txtPrecoFinalProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblItem);
        if (tblItem.getColumnModel().getColumnCount() > 0) {
            tblItem.getColumnModel().getColumn(3).setHeaderValue("Unidade de medida");
        }

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel18.setText("Itens");

        btnProx.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnProx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-à-direita-dentro-de-um-círculo-16_1.png"))); // NOI18N
        btnProx.setText("Próximo");
        btnProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-cancelar-16.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAlimenticio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMaterial))
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnExcluir)
                            .addGap(18, 18, 18)
                            .addComponent(btnProx))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel18)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmbAlimenticio)
                    .addComponent(cmbMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProx)
                    .addComponent(btnExcluir))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos/materiais", jPanel3);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel28.setText("Funcionários incluídos no pacote");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-detetive-16.png"))); // NOI18N
        jLabel29.setText("Busca:");

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setText("Nome:");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setText("Celular/ Telefone:");

        btnIncluirFunc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnIncluirFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-mais-16.png"))); // NOI18N
        btnIncluirFunc.setText("Incluir funcinário");
        btnIncluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirFuncActionPerformed(evt);
            }
        });

        txtNomeFunc.setEditable(false);
        txtNomeFunc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNomeFunc.setEnabled(false);

        txtCelFunc.setEditable(false);
        txtCelFunc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCelFunc.setEnabled(false);

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel44.setText("Função:");

        txtFuncaoFunc.setEditable(false);
        txtFuncaoFunc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtFuncaoFunc.setEnabled(false);

        jLabel58.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel58.setText("Salário:");

        txtSalFunc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeFunc))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSalFunc)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFuncaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnIncluirFunc))))
                .addGap(70, 70, 70))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtCelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(txtFuncaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirFunc)
                    .addComponent(jLabel58)
                    .addComponent(txtSalFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblFuncIncluido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Função", "Celular", "Salário"
            }
        ));
        jScrollPane4.setViewportView(tblFuncIncluido);

        tblFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblFuncionario);

        jLabel57.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel57.setText("Equipe");

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-à-direita-dentro-de-um-círculo-16_1.png"))); // NOI18N
        jButton7.setText("Próximo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnExcluir1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-cancelar-16.png"))); // NOI18N
        btnExcluir1.setText("Excluir");
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnExcluir1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel57)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jLabel28)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(btnExcluir1))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Escalar equipe", jPanel8);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtValorEquipe.setEditable(false);
        txtValorEquipe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtValorDesconto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtValorDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorDescontoKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Valor do serviço:");

        txtValorServico.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtValorServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorServicoKeyReleased(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel23.setText("Orçamento");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setText("Valor de todos os itens:");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Valor da equipe:");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Desconto:");

        txtValorItens.setEditable(false);
        txtValorItens.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel43.setText("Valor final:");

        txtValorFinal.setEditable(false);
        txtValorFinal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnProxOrc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnProxOrc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-à-direita-dentro-de-um-círculo-16_1.png"))); // NOI18N
        btnProxOrc.setText("Próximo");
        btnProxOrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxOrcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23)
                    .addComponent(txtValorServico)
                    .addComponent(txtValorItens)
                    .addComponent(txtValorEquipe)
                    .addComponent(txtValorDesconto)
                    .addComponent(txtValorFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(btnProxOrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel23)
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtValorItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtValorEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtValorDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnProxOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Orçamento", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel32.setText("Fatura");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 33, -1, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setText("Nome do cliente:");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setText("Data de vencimento:");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel36.setText("Valor original:");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        txtValorOriginal.setEditable(false);
        txtValorOriginal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel6.add(txtValorOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 90, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel37.setText("Foma de pagamento:");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel38.setText("Subtotal:");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel39.setText("Descontos:");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel40.setText("Valor por parcela:");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel41.setText("Total:");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel42.setText("Nº de parcelas:");

        cmbPagamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "À vista", "Parcelado" }));

        txtParcelas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtParcelasKeyReleased(evt);
            }
        });

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSubtotal.setEnabled(false);

        txtDescontoParcela.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDescontoParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoParcelaKeyReleased(evt);
            }
        });

        txtValorParcela.setEditable(false);
        txtValorParcela.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtValorParcela.setEnabled(false);

        txtTotalParcela.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTotalParcela.setEnabled(false);

        btnFatura.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnFatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-recibo-em-dinheiro-16.png"))); // NOI18N
        btnFatura.setText("Gerar Fatura de Pagamento");
        btnFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel37)
                            .addGap(18, 18, 18)
                            .addComponent(cmbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel42)
                                        .addComponent(jLabel38)
                                        .addComponent(jLabel39))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtParcelas)
                                        .addComponent(txtSubtotal)
                                        .addComponent(txtDescontoParcela)))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jLabel40)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jLabel41)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtTotalParcela)))
                                    .addGap(0, 2, Short.MAX_VALUE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cmbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescontoParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtTotalParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFatura)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 8, 280, -1));

        btnInserir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-recibo-em-dinheiro-16.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        jPanel6.add(btnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 180, -1));

        txtValorEntrada.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel6.add(txtValorEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 149, 30));

        jLabel54.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel54.setText("Valor de entrada:");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        table.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.setRowHeight(30);
        jScrollPane7.setViewportView(table);

        jPanel6.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 820, 164));

        btnSalvar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-ok-16.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel6.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, -1, -1));

        cmbOrcamento.setEditable(true);
        cmbOrcamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbOrcamento.setToolTipText("");
        cmbOrcamento.setEnabled(false);
        jPanel6.add(cmbOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 80, -1));

        cmbCliente1.setEditable(true);
        cmbCliente1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbCliente1.setToolTipText("");
        cmbCliente1.setEnabled(false);
        jPanel6.add(cmbCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 350, -1));

        try {
            txtDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVencimento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDataVencimento.setToolTipText("");
        jPanel6.add(txtDataVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, -1));

        cmbId.setEditable(true);
        cmbId.setEnabled(false);
        jPanel6.add(cmbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 80, -1));

        jTabbedPane1.addTab("Dados da fatura", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        atualizarTabelaProduto();
        atualizarTabelaEquipe();
        atualizarComboCliente();
        atualizarTabelaEquipe();
        if (objetoOrcamento != null) {
            cmbCliente.setSelectedItem(objetoOrcamento.getIdCliente());
            cmbTipoEvento.setSelectedItem(objetoOrcamento.getTipo());
            lblNumeroConvidados.setText(objetoOrcamento.getConvidados() + "");
            lblDias.setText(objetoOrcamento.getDuracao() + "");
            cmbLocal.setSelectedItem(objetoOrcamento.getLocalEvento());
            lblEndereco.setText(objetoOrcamento.getEndereco());
            lblDescricao.setText(objetoOrcamento.getDescricao());
        }

    }//GEN-LAST:event_formWindowActivated

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        objetoPacote = new entity.Pacote();

        for (int i = 0, linha = 0; i < modelProd.getRowCount(); i++, linha++) {
            objetoPacote.setNomeProduto(modelProd.getValueAt(linha, 0) + "");
            objetoPacote.setQtdProduto(Integer.parseInt(modelProd.getValueAt(linha, 1) + ""));
            linha = 0;
            if(i < modelFunc.getRowCount()){
                objetoPacote.setNomeFuncionario(modelFunc.getValueAt(i, 0) + "");
                objetoPacote.setFuncaoFuncionario(modelFunc.getValueAt(i, 1) + "");
                objetoPacote.setOrcamentoIdp((Orcamento) cmbOrcamento.getSelectedItem());
                objetoPacote.setIdGambiarra(Integer.parseInt(cmbOrcamento.getSelectedItem() + ""));
            }
            new PacoteDAO().inserir(objetoPacote);
        }
        JOptionPane.showMessageDialog(this, "Salvo com sucesso", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturaActionPerformed
        objetoLancamento = new entity.Lancamento();
        int parcelas = Integer.parseInt(txtParcelas.getText());
        
        Date hoje = Calendar.getInstance().getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();
        Date date = null;
        try {
            date = dateFormat.parse(txtDataVencimento.getText());
        } catch (ParseException ex) {
            Logger.getLogger(Novo_evento.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 1; i <= parcelas; i++) {
            objetoLancamento.setParcela(i);
            objetoLancamento.setAbertura(hoje + "");
            objetoLancamento.setVencimento(date);
            objetoLancamento.setTipoLancamento(cmbPagamento.getSelectedItem() + "");
            objetoLancamento.setStatusLancamento("Em andamento");
            objetoLancamento.setValorEntrada(Double.parseDouble(txtValorParcela.getText()));
            objetoLancamento.setOrcamentoId((Orcamento) cmbOrcamento.getSelectedItem());
            objetoLancamento.setIl(Integer.parseInt(cmbId.getSelectedItem() + ""));

            cal.setTime(date);
            cal.add(Calendar.MONTH, 1);
            date = cal.getTime();
            
            new dao.LancamentoDAO().inserir(objetoLancamento);
        }
        
        atualizarLancamento();
        
//        modelLanc = (DefaultTableModel) table.getModel();
//        for (int i = 0; i < modelLanc.getRowCount() ; i++) {
//            if(table.getValueAt(i, 2) != cmbId.getSelectedItem()) modelLanc.removeRow(i);
//        }
    }//GEN-LAST:event_btnFaturaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        Date hoje = Calendar.getInstance().getTime();
        
        if (objetoLancamento == null) {
            objetoLancamento = new entity.Lancamento();
        }

        objetoLancamento.setParcela(0);
        objetoLancamento.setAbertura(hoje + "");
        objetoLancamento.setVencimento(null);
        objetoLancamento.setTipoLancamento("Cartão");
        objetoLancamento.setStatusLancamento("OK");
        objetoLancamento.setValorEntrada(Double.parseDouble(txtValorEntrada.getText()));
        objetoLancamento.setOrcamentoId((Orcamento) cmbOrcamento.getSelectedItem());
        objetoLancamento.setIl(Integer.parseInt(cmbId.getSelectedItem() + ""));

        if (objetoLancamento == null) {
            new dao.LancamentoDAO().inserir(objetoLancamento);
        } else {
            new dao.LancamentoDAO().editar(objetoLancamento);
        }

        double entrada = Double.parseDouble(txtValorEntrada.getText());
        double subtotal = Double.parseDouble(txtSubtotal.getText());
        txtSubtotal.setText(subtotal - entrada + "");
              
        atualizarLancamento();
        
//        for (int i = 0; i < table.getModel().getRowCount() ; i++) {
//            if(table.getModel().getValueAt(i, 2) != cmbId.getSelectedItem()) table.removeRowSelectionInterval(i, i+1);
//        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        JTable tabela = (JTable) evt.getSource();
        int linha = tabela.rowAtPoint(evt.getPoint());
        for (int i = 0; i < tabela.getModel().getColumnCount(); i++) {
            String nomeColuna = tabela.getModel().getColumnName(i);
            if (nomeColuna.trim().equals("Id Produto")) {
                idSelecionado = Integer.parseInt(tabela.getValueAt(linha, i) + "");
                break;
            }
        }
        entity.Produto produto = new ProdutoDAO().selecionarPorCodigo(idSelecionado);
        txtNomeProduto.setText(produto.getNomeProduto());
        txtTipoProduto.setText(produto.getTipo());
        txtValorProd.setText(produto.getValorProduto().toString());
        txtUnidadeProd.setText(produto.getUnidadeMedida());
    }//GEN-LAST:event_tblItemMouseClicked

    private void tblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionarioMouseClicked
        JTable tabela = (JTable) evt.getSource();
        int linha = tabela.rowAtPoint(evt.getPoint());
        for (int i = 0; i < tabela.getModel().getColumnCount(); i++) {
            String nomeColuna = tabela.getModel().getColumnName(i);
            if (nomeColuna.trim().equals("Id Funcionario")) {
                idSelecionado = Integer.parseInt(tabela.getValueAt(linha, i) + "");
                break;
            }
        }
        entity.Funcionario funcionario = new FuncionarioDAO().selecionarPorCodigo(idSelecionado);
        txtNomeFunc.setText(funcionario.getNomeFuncionario());
        txtCelFunc.setText(funcionario.getCelular());
        txtSalFunc.setText(funcionario.getSalario().toString());
        txtFuncaoFunc.setText(funcionario.getFuncao());


    }//GEN-LAST:event_tblFuncionarioMouseClicked

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        if (modelProd == null) {
            modelProd = (DefaultTableModel) tblItemIncluido.getModel();
        }
        modelProd.addRow(new Object[]{txtNomeProduto.getText(), txtQtdProd.getText(), txtTipoProduto.getText(), txtPrecoFinalProd.getText(),});
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void cmbAlimenticioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlimenticioActionPerformed
        try {
            if (cmbMaterial.isSelected() && cmbAlimenticio.isSelected()) {
                List<Produto> results = new ProdutoDAO().selecionarTodos();
                TableModel tableModelProdutosAli = TableModelCreator.createTableModel(Produto.class, results, null);
                tblItem.setModel(tableModelProdutosAli);
            } else if (cmbMaterial.isSelected() && !cmbAlimenticio.isSelected()) {
                List<Produto> results = new ProdutoDAO().findByName("Material");
                TableModel tableModelProdutosAli = TableModelCreator.createTableModel(Produto.class, results, null);
                tblItem.setModel(tableModelProdutosAli);
            } else if (cmbAlimenticio.isSelected()) {
                List<Produto> results = new ProdutoDAO().findByName("Alimentício");
                TableModel tableModelProdutosAli = TableModelCreator.createTableModel(Produto.class, results, null);
                tblItem.setModel(tableModelProdutosAli);
            } else {
                List<Produto> results = new ProdutoDAO().selecionarTodos();
                TableModel tableModelProdutosAli = TableModelCreator.createTableModel(Produto.class, results, null);
                tblItem.setModel(tableModelProdutosAli);
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_cmbAlimenticioActionPerformed

    private void cmbMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMaterialActionPerformed
        try {
            if (cmbMaterial.isSelected() && cmbAlimenticio.isSelected()) {
                List<Produto> results = new ProdutoDAO().selecionarTodos();
                TableModel tableModelProdutosAli = TableModelCreator.createTableModel(Produto.class, results, null);
                tblItem.setModel(tableModelProdutosAli);
            } else if (!cmbMaterial.isSelected() && cmbAlimenticio.isSelected()) {
                List<Produto> results = new ProdutoDAO().findByName("Alimentício");
                TableModel tableModelProdutosAli = TableModelCreator.createTableModel(Produto.class, results, null);
                tblItem.setModel(tableModelProdutosAli);
            } else if (cmbMaterial.isSelected()) {
                List<Produto> results = new ProdutoDAO().findByName("Material");
                TableModel tableModelProdutosAli = TableModelCreator.createTableModel(Produto.class, results, null);
                tblItem.setModel(tableModelProdutosAli);
            } else {
                List<Produto> results = new ProdutoDAO().selecionarTodos();
                TableModel tableModelProdutosAli = TableModelCreator.createTableModel(Produto.class, results, null);
                tblItem.setModel(tableModelProdutosAli);
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_cmbMaterialActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        modelProd = (DefaultTableModel) tblItemIncluido.getModel();

        if (tblItemIncluido.getSelectedRowCount() == 1)
            modelProd.removeRow(tblItemIncluido.getSelectedRow());
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxActionPerformed
        double salario = 0;

        for (int i = 0; i < tblItemIncluido.getRowCount(); i++) {
            salario += Double.parseDouble(modelProd.getValueAt(i, 3) + "");
        }
        txtValorItens.setText(salario + "");

        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnProxActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        modelFunc = (DefaultTableModel) tblFuncIncluido.getModel();

        if (tblFuncIncluido.getSelectedRowCount() == 1) {
            modelFunc.removeRow(tblFuncIncluido.getSelectedRow());
        }
    }

    private void btnIncluFuncActionPerformed(java.awt.event.ActionEvent evt) {
    }//GEN-LAST:event_btnExcluir1ActionPerformed

    private void btnIncluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirFuncActionPerformed
        if (modelFunc == null) {
            modelFunc = (DefaultTableModel) tblFuncIncluido.getModel();
        }
        modelFunc.addRow(new Object[]{txtNomeFunc.getText(), txtFuncaoFunc.getText(), txtCelFunc.getText(), txtSalFunc.getText()});
    }//GEN-LAST:event_btnIncluirFuncActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        double salario = 0;

        for (int i = 0; i < tblFuncIncluido.getRowCount(); i++) {
            salario += Double.parseDouble(modelFunc.getValueAt(i, 3) + "");
        }
        txtValorEquipe.setText(salario + "");
        double valorItens = Double.parseDouble(txtValorItens.getText());
        double valorEquipe = Double.parseDouble(txtValorEquipe.getText());
        txtValorFinal.setText(valorEquipe + valorItens + "");
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnProxOrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxOrcActionPerformed
        if (objetoOrcamento == null) {
            objetoOrcamento = new Orcamento();
        }

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = null;
        try {
            date = dateFormat.parse(lblData1.getText() + " " + lblHoraroi.getText());
        } catch (ParseException ex) {
            Logger.getLogger(Novo_evento.class.getName()).log(Level.SEVERE, null, ex);
        }

        objetoOrcamento.setIdCliente((entity.Cliente) cmbCliente.getSelectedItem());
        objetoOrcamento.setTipo(cmbTipoEvento.getSelectedItem() + "");
        objetoOrcamento.setConvidados(Integer.parseInt(lblNumeroConvidados.getText()));
        objetoOrcamento.setDuracao(Integer.parseInt(lblDias.getText()));
        objetoOrcamento.setLocalEvento(cmbLocal.getSelectedItem() + "");
        objetoOrcamento.setDataHorario(date);
        objetoOrcamento.setEndereco(lblEndereco.getText());
        objetoOrcamento.setDescricao(lblDescricao.getText());
        objetoOrcamento.setValorFinal(Double.parseDouble(txtValorFinal.getText()));
        objetoOrcamento.setValorEquipe(Double.parseDouble(txtValorEquipe.getText()));
        objetoOrcamento.setValorServico(Double.parseDouble(txtValorServico.getText()));
        objetoOrcamento.setDeconto(Double.parseDouble(txtValorDesconto.getText()));

        if (objetoOrcamento == null) {
            new OrcamentoDAO().inserir(objetoOrcamento);
        } else {
            new OrcamentoDAO().editar(objetoOrcamento);
        }

        txtValorOriginal.setText(txtValorFinal.getText());
        cmbCliente1.setSelectedItem(cmbCliente.getSelectedItem());
        txtSubtotal.setText(txtValorFinal.getText());
        equipe = Double.parseDouble(txtValorEquipe.getText());
      
        atualizarOrcamento();
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnProxOrcActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnProximoActionPerformed

    private void txtQtdProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdProdKeyReleased
        // TODO add your handling code here:
        try {
            int qtd = Integer.parseInt(txtQtdProd.getText());
            double preco = Double.parseDouble(txtValorProd.getText());
            txtPrecoFinalProd.setText((qtd * preco )+ "");
        } catch (Exception ex) {
            txtPrecoFinalProd.setText("");
        }
    }//GEN-LAST:event_txtQtdProdKeyReleased

    private void txtValorServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorServicoKeyReleased
        try{
            double valorServico = Double.parseDouble(txtValorServico.getText());
            double valorItens = Double.parseDouble(txtValorItens.getText());
            double valorEquipe = Double.parseDouble(txtValorEquipe.getText());

            double valorFinal = (valorServico + valorItens + valorEquipe);
            txtValorFinal.setText(valorFinal + "");
        } catch (Exception ex){
            txtValorFinal.setText("");
        }
    }//GEN-LAST:event_txtValorServicoKeyReleased

    private void txtValorDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDescontoKeyReleased
        try{
            double valorServico = Double.parseDouble(txtValorServico.getText());
            double valorItens = Double.parseDouble(txtValorItens.getText());
            double valorEquipe = Double.parseDouble(txtValorEquipe.getText());
            double desconto = Double.parseDouble(txtValorDesconto.getText());

            double valorFinal = (valorServico + valorItens + valorEquipe - desconto);
            txtValorFinal.setText(valorFinal + "");
        } catch (Exception ex){
            txtValorFinal.setText("");
        }
    }//GEN-LAST:event_txtValorDescontoKeyReleased

    private void txtParcelasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParcelasKeyReleased
        try {
            double parcelas = Double.parseDouble(txtParcelas.getText());
            double subtotal = Double.parseDouble(txtSubtotal.getText());

            txtValorParcela.setText(Math.round(subtotal/ parcelas) + "");
            double valorParcela = Double.parseDouble(txtValorParcela.getText());
            txtTotalParcela.setText(Math.round(valorParcela * parcelas) + "");
        } catch (Exception e) {
            txtTotalParcela.setText("");
        }
    }//GEN-LAST:event_txtParcelasKeyReleased

    private void txtDescontoParcelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoParcelaKeyReleased
        try {
            double desconto = Double.parseDouble(txtDescontoParcela.getText());
            double parcelas = Double.parseDouble(txtParcelas.getText());
            double subtotal = Double.parseDouble(txtSubtotal.getText());

            txtValorParcela.setText(Math.round((subtotal - desconto)/ parcelas) + "");
            double valorParcela = Double.parseDouble(txtValorParcela.getText());
            txtTotalParcela.setText(Math.round(valorParcela * parcelas) + "");
        } catch (Exception e) {
            txtTotalParcela.setText("");
        }
    }//GEN-LAST:event_txtDescontoParcelaKeyReleased

    private void atualizarComboCliente() {
        if (clienteSelecionado != null) {

        } else {
            try {
                List<entity.Cliente> listaCliente = new ClienteDAO().selecionarTodos();
                cmbCliente.setModel(new DefaultComboBoxModel<entity.Cliente>(listaCliente.toArray(new entity.Cliente[listaCliente.size()])));
                //cmbCliente1.setModel(new DefaultComboBoxModel<entity.Cliente>(listaCliente.toArray(new entity.Cliente[listaCliente.size()])));
            } catch (Exception ex) {

            }
        }

    }

    private void atualizarLancamento() {
        try {
            List<entity.Lancamento> listaProdutos = new dao.LancamentoDAO().findOrcamentoIdLanc(Integer.parseInt(cmbId.getSelectedItem() + ""));
            table.setModel(utils.TableModelCreator.createTableModel(entity.Lancamento.class, listaProdutos, null));
        } catch (Exception ex) {

        }
    }

    private void atualizarOrcamento() {
        try {
            List<Orcamento> results = new OrcamentoDAO().findOrcamentoId();
            cmbOrcamento.setModel(new DefaultComboBoxModel<entity.Orcamento>(results.toArray(new entity.Orcamento[results.size()])));
            cmbId.setSelectedItem(cmbOrcamento.getSelectedItem().toString());
        } catch (Exception ex) {

        }
    }

    private void atualizarTabelaProduto() {
        try {
            List<Produto> results = new ProdutoDAO().selecionarTodos();
            TableModel tableModelProdutosAli = TableModelCreator.createTableModel(Produto.class, results, null);
            tblItem.setModel(tableModelProdutosAli);
        } catch (Exception ex) {

        }
    }

    private void atualizarTabelaEquipe() {
        try {
            List<entity.Funcionario> listaFuncionarios = new FuncionarioDAO().selecionarTodos();
            TableModel tableModelFuncionarios = TableModelCreator.createTableModel(entity.Funcionario.class, listaFuncionarios, null);
            tblFuncionario.setModel(tableModelFuncionarios);
        } catch (Exception ex) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Novo_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Novo_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Novo_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Novo_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Novo_evento dialog = new Novo_evento(new javax.swing.JFrame(), true, null, null, null, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnFatura;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnIncluirFunc;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnProx;
    private javax.swing.JButton btnProxOrc;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JRadioButton cmbAlimenticio;
    private javax.swing.JComboBox<entity.Cliente> cmbCliente;
    private javax.swing.JComboBox<String> cmbCliente1;
    private javax.swing.JComboBox<String> cmbId;
    private javax.swing.JComboBox<String> cmbLocal;
    private javax.swing.JRadioButton cmbMaterial;
    private javax.swing.JComboBox<entity.Orcamento> cmbOrcamento;
    private javax.swing.JComboBox<String> cmbPagamento;
    private javax.swing.JComboBox<String> cmbTipoEvento;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JFormattedTextField lblData1;
    private javax.swing.JTextField lblDescricao;
    private javax.swing.JTextField lblDias;
    private javax.swing.JTextField lblEndereco;
    private javax.swing.JFormattedTextField lblHoraroi;
    private javax.swing.JTextField lblNumeroConvidados;
    private javax.swing.JTable table;
    private javax.swing.JTable tblFuncIncluido;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblItemIncluido;
    private javax.swing.JTextField txtCelFunc;
    private javax.swing.JFormattedTextField txtDataVencimento;
    private javax.swing.JTextField txtDescontoParcela;
    private javax.swing.JTextField txtFuncaoFunc;
    private javax.swing.JTextField txtNomeFunc;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtParcelas;
    private javax.swing.JTextField txtPrecoFinalProd;
    private javax.swing.JTextField txtQtdProd;
    private javax.swing.JTextField txtSalFunc;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTipoProduto;
    private javax.swing.JTextField txtTotalParcela;
    private javax.swing.JTextField txtUnidadeProd;
    private javax.swing.JTextField txtValorDesconto;
    private javax.swing.JTextField txtValorEntrada;
    private javax.swing.JTextField txtValorEquipe;
    private javax.swing.JTextField txtValorFinal;
    private javax.swing.JTextField txtValorItens;
    private javax.swing.JTextField txtValorOriginal;
    private javax.swing.JTextField txtValorParcela;
    private javax.swing.JTextField txtValorProd;
    private javax.swing.JTextField txtValorServico;
    // End of variables declaration//GEN-END:variables
}
